### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zyc801208** [lexxvir/zmodem#1]
src/crc.rs#79 
before:
crc = update(crc, &*IEEE_TABLE, &[x]);
after:
crc = update(crc, &IEEE_TABLE, &[x]);

**Comment by lexxvir** [comment]
Hi @zyc801208,

What rustc version did you try?

I've checked master on rustc 1.41.0, there is no compilation error.

**Comment by zyc801208** [comment]
cargo version
cargo 1.41.0 (626f0f40e 2019-12-03)


error[E0614]: type `[u32; 256]` cannot be dereferenced
  --> src/crc.rs:79:28
   |
79 |         crc = update(crc, &*IEEE_TABLE, &[x]);

**Comment by zyc801208** [comment]
another question, Can i use zmodem to transfer file in a SSH connection.  
The effect is equal to ZSSH  rz/sz

**Comment by lexxvir** [comment]
Thanks! It was old `Cargo.lock` issue.

> Can i use zmodem to transfer file in a SSH connection.

Sorry, personally I did not use zmodem in SSH connection, so I have no answer.
