### ISSUE TITLE
Make license explicit

### ISSUE THREAD

**Issue by matt-har-vey** [lexxvir/zmodem#2]
Thanks for writing this. It is much easier to follow than the original rz.c.

I'd like to adapt this for use in a work project, but I am not permitted to do that without an explicit license.

Have you considered what, if any, license you intend this to have?

(For my purposes, just a reference to Apache-2.0 in Cargo.toml would be perfect. https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields)

**Comment by lexxvir** [comment]
I'm glad that your found this crate is useful for you. It's somehow abandoned at the time. But I've added the license field in the Cargo.toml. Hope this help using this crate in your projects.
